2021-03-30 18:13:42,262 : INFO : root : Loading config.
2021-03-30 18:13:42,269 : INFO : YamlMultifileConfigLoader : Machine config file #1: config.yaml
2021-03-30 18:13:42,270 : INFO : ConfigProcessor : Loading config from cache: C:\Users\Noah\AppData\Local\Temp\f1e6b3d603b69cf20c882e489c97a885.mpf_cache
2021-03-30 18:13:42,376 : INFO : ConfigProcessor : Loading config from cache: C:\Users\Noah\AppData\Local\Temp\3667aa7b16c33035bf5ed76426078541.mpf_cache
2021-03-30 18:13:42,377 : INFO : ConfigProcessor : Loading config from cache: C:\Users\Noah\AppData\Local\Temp\a7eac71e9da1e9cfd4db34c71351dbda.mpf_cache
2021-03-30 18:13:42,378 : INFO : ConfigProcessor : Loading config from cache: C:\Users\Noah\AppData\Local\Temp\087a53a03e25f86845675c231fd2982a.mpf_cache
2021-03-30 18:13:42,380 : INFO : ConfigProcessor : Loading config from cache: C:\Users\Noah\AppData\Local\Temp\8252fe0f7adb2196fe883aefa2a8963e.mpf_cache
2021-03-30 18:13:42,381 : INFO : ConfigProcessor : Loading config from cache: C:\Users\Noah\AppData\Local\Temp\fab15a6988082b7b90a1ae2ab7ba49ba.mpf_cache
2021-03-30 18:13:42,382 : INFO : Machine : Mission Pinball Framework Core Engine v0.54.6
2021-03-30 18:13:42,382 : INFO : Machine : Command line arguments: {'no_load_cache': False, 'create_config_cache': True, 'bcp': False, 'configfile': ['config.yaml'], 'force_assets_load': False, 'jsonlogging': False, 'logfile': 'logs\\2021-03-30-18-13-42-mpf-DESKTOP-VL0THH1.log', 'pause': False, 'production': False, 'text_ui': False, 'loglevel': 15, 'consoleloglevel': 20, 'force_platform': None, 'syslog_address': None, 'mc_file_name': None, 'no_sound': False}
2021-03-30 18:13:42,382 : INFO : Machine : MPF path: c:\users\noah\mpfenv\lib\site-packages\mpf
2021-03-30 18:13:42,382 : INFO : Machine : Machine path: C:\Users\Noah\work\Andy Cavatorta\pinball\notes\MPF\test_platform
2021-03-30 18:13:42,382 : INFO : Machine : Platform: win32
2021-03-30 18:13:42,382 : INFO : Machine : Python executable location: c:\users\noah\mpfenv\scripts\python.exe
2021-03-30 18:13:42,382 : INFO : Machine : Python version: 3.7.9 (64-bit)
2021-03-30 18:13:42,386 : INFO : Machine : Initialise MPF.
2021-03-30 18:13:42,501 : INFO : P-Roc : Connecting to P-ROC
2021-03-30 18:13:42,742 : INFO : P-Roc : Successfully connected to P-ROC/P3-ROC. Firmware Version: 2. Firmware Revision: 6. Hardware Board ID: 1
2021-03-30 18:13:42,742 : WARNING : P-Roc : Consider upgrading the firmware of your P/P3-Roc to at least 2.14. Your version contains known bugs.
2021-03-30 18:13:42,907 : INFO : EventManager : Event: ======'machine_var_p_roc_version'====== Args={'value': 2, 'prev_value': None, 'change': True}
2021-03-30 18:13:42,907 : INFO : EventManager : Event: ======'machine_var_p_roc_revision'====== Args={'value': 6, 'prev_value': None, 'change': True}
2021-03-30 18:13:42,907 : INFO : EventManager : Event: ======'machine_var_p_roc_hardware_version'====== Args={'value': 1, 'prev_value': None, 'change': True}
2021-03-30 18:13:42,908 : INFO : EventManager : Event: ======'machine_var_credits_string'====== Args={'value': 'FREE PLAY', 'prev_value': None, 'change': True}
2021-03-30 18:13:42,978 : INFO : EventManager : Event: ======'machine_var_mpf_version'====== Args={'value': 'MPF v0.54.6', 'prev_value': None, 'change': True}
2021-03-30 18:13:42,978 : INFO : EventManager : Event: ======'machine_var_mpf_extended_version'====== Args={'value': 'MPF v0.54.6, Config version:5, Show version: 5, BCP version:1.1', 'prev_value': None, 'change': True}
2021-03-30 18:13:42,978 : INFO : EventManager : Event: ======'machine_var_python_version'====== Args={'value': '3.7.9', 'prev_value': None, 'change': True}
2021-03-30 18:13:42,979 : INFO : EventManager : Event: ======'machine_var_platform'====== Args={'value': 'Windows-10-10.0.19041-SP0', 'prev_value': None, 'change': True}
2021-03-30 18:13:42,979 : INFO : EventManager : Event: ======'machine_var_platform_system'====== Args={'value': 'Windows', 'prev_value': None, 'change': True}
2021-03-30 18:13:42,979 : INFO : EventManager : Event: ======'machine_var_platform_release'====== Args={'value': '10', 'prev_value': None, 'change': True}
2021-03-30 18:13:42,979 : INFO : EventManager : Event: ======'machine_var_platform_version'====== Args={'value': '10.0.19041', 'prev_value': None, 'change': True}
2021-03-30 18:13:42,979 : INFO : EventManager : Event: ======'machine_var_platform_machine'====== Args={'value': 'AMD64', 'prev_value': None, 'change': True}
2021-03-30 18:13:42,979 : INFO : EventManager : Event: ======'init_phase_1'====== Args={}
2021-03-30 18:13:43,080 : INFO : EventManager : Event: ======'drop_target_bank_drop_target_bank_1_up'====== Args={}
2021-03-30 18:13:43,150 : ERROR : asyncio : Task exception was never retrieved
future: <Task finished coro=<SystemWideDevice.device_added_system_wide() done, defined at c:\users\noah\mpfenv\lib\site-packages\mpf\core\system_wide_device.py:15> exception=AttributeError("'PDBSwitch' object has no attribute 'machine_type'")>
Traceback (most recent call last):
  File "c:\users\noah\mpfenv\lib\site-packages\mpf\core\system_wide_device.py", line 17, in device_added_system_wide
    await self._initialize()
  File "c:\users\noah\mpfenv\lib\site-packages\mpf\devices\switch.py", line 148, in _initialize
    self.config['number'], config, self.config['platform_settings'])
  File "c:\users\noah\mpfenv\lib\site-packages\mpf\platforms\p3_roc.py", line 371, in configure_switch
    proc_num = self.pdbconfig.get_proc_switch_number(str(number))
  File "c:\users\noah\mpfenv\lib\site-packages\mpf\platforms\p_roc_common.py", line 1193, in get_proc_switch_number
    switch = PDBSwitch(self, number_str)
  File "c:\users\noah\mpfenv\lib\site-packages\mpf\platforms\p_roc_devices.py", line 226, in __init__
    print( self.machine_type );
AttributeError: 'PDBSwitch' object has no attribute 'machine_type'
2021-03-30 18:13:43,167 : ERROR : asyncio : Task exception was never retrieved
future: <Task finished coro=<SystemWideDevice.device_added_system_wide() done, defined at c:\users\noah\mpfenv\lib\site-packages\mpf\core\system_wide_device.py:15> exception=AttributeError("'PDBSwitch' object has no attribute 'machine_type'")>
Traceback (most recent call last):
  File "c:\users\noah\mpfenv\lib\site-packages\mpf\core\system_wide_device.py", line 17, in device_added_system_wide
    await self._initialize()
  File "c:\users\noah\mpfenv\lib\site-packages\mpf\devices\switch.py", line 148, in _initialize
    self.config['number'], config, self.config['platform_settings'])
  File "c:\users\noah\mpfenv\lib\site-packages\mpf\platforms\p3_roc.py", line 371, in configure_switch
    proc_num = self.pdbconfig.get_proc_switch_number(str(number))
  File "c:\users\noah\mpfenv\lib\site-packages\mpf\platforms\p_roc_common.py", line 1193, in get_proc_switch_number
    switch = PDBSwitch(self, number_str)
  File "c:\users\noah\mpfenv\lib\site-packages\mpf\platforms\p_roc_devices.py", line 226, in __init__
    print( self.machine_type );
AttributeError: 'PDBSwitch' object has no attribute 'machine_type'
2021-03-30 18:13:43,168 : ERROR : asyncio : Task exception was never retrieved
future: <Task finished coro=<SystemWideDevice.device_added_system_wide() done, defined at c:\users\noah\mpfenv\lib\site-packages\mpf\core\system_wide_device.py:15> exception=AttributeError("'PDBSwitch' object has no attribute 'machine_type'")>
Traceback (most recent call last):
  File "c:\users\noah\mpfenv\lib\site-packages\mpf\core\system_wide_device.py", line 17, in device_added_system_wide
    await self._initialize()
  File "c:\users\noah\mpfenv\lib\site-packages\mpf\devices\switch.py", line 148, in _initialize
    self.config['number'], config, self.config['platform_settings'])
  File "c:\users\noah\mpfenv\lib\site-packages\mpf\platforms\p3_roc.py", line 371, in configure_switch
    proc_num = self.pdbconfig.get_proc_switch_number(str(number))
  File "c:\users\noah\mpfenv\lib\site-packages\mpf\platforms\p_roc_common.py", line 1193, in get_proc_switch_number
    switch = PDBSwitch(self, number_str)
  File "c:\users\noah\mpfenv\lib\site-packages\mpf\platforms\p_roc_devices.py", line 226, in __init__
    print( self.machine_type );
AttributeError: 'PDBSwitch' object has no attribute 'machine_type'
2021-03-30 18:13:43,170 : ERROR : asyncio : Task exception was never retrieved
future: <Task finished coro=<SystemWideDevice.device_added_system_wide() done, defined at c:\users\noah\mpfenv\lib\site-packages\mpf\core\system_wide_device.py:15> exception=AttributeError("'PDBSwitch' object has no attribute 'machine_type'")>
Traceback (most recent call last):
  File "c:\users\noah\mpfenv\lib\site-packages\mpf\core\system_wide_device.py", line 17, in device_added_system_wide
    await self._initialize()
  File "c:\users\noah\mpfenv\lib\site-packages\mpf\devices\switch.py", line 148, in _initialize
    self.config['number'], config, self.config['platform_settings'])
  File "c:\users\noah\mpfenv\lib\site-packages\mpf\platforms\p3_roc.py", line 371, in configure_switch
    proc_num = self.pdbconfig.get_proc_switch_number(str(number))
  File "c:\users\noah\mpfenv\lib\site-packages\mpf\platforms\p_roc_common.py", line 1193, in get_proc_switch_number
    switch = PDBSwitch(self, number_str)
  File "c:\users\noah\mpfenv\lib\site-packages\mpf\platforms\p_roc_devices.py", line 226, in __init__
    print( self.machine_type );
AttributeError: 'PDBSwitch' object has no attribute 'machine_type'
2021-03-30 18:13:43,172 : ERROR : asyncio : Task exception was never retrieved
future: <Task finished coro=<SystemWideDevice.device_added_system_wide() done, defined at c:\users\noah\mpfenv\lib\site-packages\mpf\core\system_wide_device.py:15> exception=AttributeError("'PDBSwitch' object has no attribute 'machine_type'")>
Traceback (most recent call last):
  File "c:\users\noah\mpfenv\lib\site-packages\mpf\core\system_wide_device.py", line 17, in device_added_system_wide
    await self._initialize()
  File "c:\users\noah\mpfenv\lib\site-packages\mpf\devices\switch.py", line 148, in _initialize
    self.config['number'], config, self.config['platform_settings'])
  File "c:\users\noah\mpfenv\lib\site-packages\mpf\platforms\p3_roc.py", line 371, in configure_switch
    proc_num = self.pdbconfig.get_proc_switch_number(str(number))
  File "c:\users\noah\mpfenv\lib\site-packages\mpf\platforms\p_roc_common.py", line 1193, in get_proc_switch_number
    switch = PDBSwitch(self, number_str)
  File "c:\users\noah\mpfenv\lib\site-packages\mpf\platforms\p_roc_devices.py", line 226, in __init__
    print( self.machine_type );
AttributeError: 'PDBSwitch' object has no attribute 'machine_type'
2021-03-30 18:13:43,173 : ERROR : asyncio : Task exception was never retrieved
future: <Task finished coro=<SystemWideDevice.device_added_system_wide() done, defined at c:\users\noah\mpfenv\lib\site-packages\mpf\core\system_wide_device.py:15> exception=AttributeError("'PDBSwitch' object has no attribute 'machine_type'")>
Traceback (most recent call last):
  File "c:\users\noah\mpfenv\lib\site-packages\mpf\core\system_wide_device.py", line 17, in device_added_system_wide
    await self._initialize()
  File "c:\users\noah\mpfenv\lib\site-packages\mpf\devices\switch.py", line 148, in _initialize
    self.config['number'], config, self.config['platform_settings'])
  File "c:\users\noah\mpfenv\lib\site-packages\mpf\platforms\p3_roc.py", line 371, in configure_switch
    proc_num = self.pdbconfig.get_proc_switch_number(str(number))
  File "c:\users\noah\mpfenv\lib\site-packages\mpf\platforms\p_roc_common.py", line 1193, in get_proc_switch_number
    switch = PDBSwitch(self, number_str)
  File "c:\users\noah\mpfenv\lib\site-packages\mpf\platforms\p_roc_devices.py", line 226, in __init__
    print( self.machine_type );
AttributeError: 'PDBSwitch' object has no attribute 'machine_type'
2021-03-30 18:13:43,174 : ERROR : asyncio : Task exception was never retrieved
future: <Task finished coro=<SystemWideDevice.device_added_system_wide() done, defined at c:\users\noah\mpfenv\lib\site-packages\mpf\core\system_wide_device.py:15> exception=AttributeError("'PDBSwitch' object has no attribute 'machine_type'")>
Traceback (most recent call last):
  File "c:\users\noah\mpfenv\lib\site-packages\mpf\core\system_wide_device.py", line 17, in device_added_system_wide
    await self._initialize()
  File "c:\users\noah\mpfenv\lib\site-packages\mpf\devices\switch.py", line 148, in _initialize
    self.config['number'], config, self.config['platform_settings'])
  File "c:\users\noah\mpfenv\lib\site-packages\mpf\platforms\p3_roc.py", line 371, in configure_switch
    proc_num = self.pdbconfig.get_proc_switch_number(str(number))
  File "c:\users\noah\mpfenv\lib\site-packages\mpf\platforms\p_roc_common.py", line 1193, in get_proc_switch_number
    switch = PDBSwitch(self, number_str)
  File "c:\users\noah\mpfenv\lib\site-packages\mpf\platforms\p_roc_devices.py", line 226, in __init__
    print( self.machine_type );
AttributeError: 'PDBSwitch' object has no attribute 'machine_type'
2021-03-30 18:13:43,174 : ERROR : asyncio : Task exception was never retrieved
future: <Task finished coro=<SystemWideDevice.device_added_system_wide() done, defined at c:\users\noah\mpfenv\lib\site-packages\mpf\core\system_wide_device.py:15> exception=AttributeError("'PDBSwitch' object has no attribute 'machine_type'")>
Traceback (most recent call last):
  File "c:\users\noah\mpfenv\lib\site-packages\mpf\core\system_wide_device.py", line 17, in device_added_system_wide
    await self._initialize()
  File "c:\users\noah\mpfenv\lib\site-packages\mpf\devices\switch.py", line 148, in _initialize
    self.config['number'], config, self.config['platform_settings'])
  File "c:\users\noah\mpfenv\lib\site-packages\mpf\platforms\p3_roc.py", line 371, in configure_switch
    proc_num = self.pdbconfig.get_proc_switch_number(str(number))
  File "c:\users\noah\mpfenv\lib\site-packages\mpf\platforms\p_roc_common.py", line 1193, in get_proc_switch_number
    switch = PDBSwitch(self, number_str)
  File "c:\users\noah\mpfenv\lib\site-packages\mpf\platforms\p_roc_devices.py", line 226, in __init__
    print( self.machine_type );
AttributeError: 'PDBSwitch' object has no attribute 'machine_type'
2021-03-30 18:13:43,176 : ERROR : asyncio : Task exception was never retrieved
future: <Task finished coro=<SystemWideDevice.device_added_system_wide() done, defined at c:\users\noah\mpfenv\lib\site-packages\mpf\core\system_wide_device.py:15> exception=AttributeError("'PDBSwitch' object has no attribute 'machine_type'")>
Traceback (most recent call last):
  File "c:\users\noah\mpfenv\lib\site-packages\mpf\core\system_wide_device.py", line 17, in device_added_system_wide
    await self._initialize()
  File "c:\users\noah\mpfenv\lib\site-packages\mpf\devices\switch.py", line 148, in _initialize
    self.config['number'], config, self.config['platform_settings'])
  File "c:\users\noah\mpfenv\lib\site-packages\mpf\platforms\p3_roc.py", line 371, in configure_switch
    proc_num = self.pdbconfig.get_proc_switch_number(str(number))
  File "c:\users\noah\mpfenv\lib\site-packages\mpf\platforms\p_roc_common.py", line 1193, in get_proc_switch_number
    switch = PDBSwitch(self, number_str)
  File "c:\users\noah\mpfenv\lib\site-packages\mpf\platforms\p_roc_devices.py", line 226, in __init__
    print( self.machine_type );
AttributeError: 'PDBSwitch' object has no attribute 'machine_type'
2021-03-30 18:13:43,177 : ERROR : asyncio : Task exception was never retrieved
future: <Task finished coro=<SystemWideDevice.device_added_system_wide() done, defined at c:\users\noah\mpfenv\lib\site-packages\mpf\core\system_wide_device.py:15> exception=AttributeError("'PDBSwitch' object has no attribute 'machine_type'")>
Traceback (most recent call last):
  File "c:\users\noah\mpfenv\lib\site-packages\mpf\core\system_wide_device.py", line 17, in device_added_system_wide
    await self._initialize()
  File "c:\users\noah\mpfenv\lib\site-packages\mpf\devices\switch.py", line 148, in _initialize
    self.config['number'], config, self.config['platform_settings'])
  File "c:\users\noah\mpfenv\lib\site-packages\mpf\platforms\p3_roc.py", line 371, in configure_switch
    proc_num = self.pdbconfig.get_proc_switch_number(str(number))
  File "c:\users\noah\mpfenv\lib\site-packages\mpf\platforms\p_roc_common.py", line 1193, in get_proc_switch_number
    switch = PDBSwitch(self, number_str)
  File "c:\users\noah\mpfenv\lib\site-packages\mpf\platforms\p_roc_devices.py", line 226, in __init__
    print( self.machine_type );
AttributeError: 'PDBSwitch' object has no attribute 'machine_type'
2021-03-30 18:13:43,178 : ERROR : asyncio : Task exception was never retrieved
future: <Task finished coro=<SystemWideDevice.device_added_system_wide() done, defined at c:\users\noah\mpfenv\lib\site-packages\mpf\core\system_wide_device.py:15> exception=AttributeError("'PDBSwitch' object has no attribute 'machine_type'")>
Traceback (most recent call last):
  File "c:\users\noah\mpfenv\lib\site-packages\mpf\core\system_wide_device.py", line 17, in device_added_system_wide
    await self._initialize()
  File "c:\users\noah\mpfenv\lib\site-packages\mpf\devices\switch.py", line 148, in _initialize
    self.config['number'], config, self.config['platform_settings'])
  File "c:\users\noah\mpfenv\lib\site-packages\mpf\platforms\p3_roc.py", line 371, in configure_switch
    proc_num = self.pdbconfig.get_proc_switch_number(str(number))
  File "c:\users\noah\mpfenv\lib\site-packages\mpf\platforms\p_roc_common.py", line 1193, in get_proc_switch_number
    switch = PDBSwitch(self, number_str)
  File "c:\users\noah\mpfenv\lib\site-packages\mpf\platforms\p_roc_devices.py", line 226, in __init__
    print( self.machine_type );
AttributeError: 'PDBSwitch' object has no attribute 'machine_type'
2021-03-30 18:13:43,179 : ERROR : asyncio : Task exception was never retrieved
future: <Task finished coro=<SystemWideDevice.device_added_system_wide() done, defined at c:\users\noah\mpfenv\lib\site-packages\mpf\core\system_wide_device.py:15> exception=AttributeError("'PDBSwitch' object has no attribute 'machine_type'")>
Traceback (most recent call last):
  File "c:\users\noah\mpfenv\lib\site-packages\mpf\core\system_wide_device.py", line 17, in device_added_system_wide
    await self._initialize()
  File "c:\users\noah\mpfenv\lib\site-packages\mpf\devices\switch.py", line 148, in _initialize
    self.config['number'], config, self.config['platform_settings'])
  File "c:\users\noah\mpfenv\lib\site-packages\mpf\platforms\p3_roc.py", line 371, in configure_switch
    proc_num = self.pdbconfig.get_proc_switch_number(str(number))
  File "c:\users\noah\mpfenv\lib\site-packages\mpf\platforms\p_roc_common.py", line 1193, in get_proc_switch_number
    switch = PDBSwitch(self, number_str)
  File "c:\users\noah\mpfenv\lib\site-packages\mpf\platforms\p_roc_devices.py", line 226, in __init__
    print( self.machine_type );
AttributeError: 'PDBSwitch' object has no attribute 'machine_type'
2021-03-30 18:13:43,181 : INFO : EventManager : Event: ======'init_phase_2'====== Args={}
2021-03-30 18:13:43,181 : INFO : Machine : Starting the main run loop.
2021-03-30 18:13:43,181 : INFO : Machine : Shutting down...
2021-03-30 18:13:43,181 : INFO : EventManager : Event: ======'shutdown'====== Args={}
2021-03-30 18:13:43,183 : ERROR : asyncio : Task exception was never retrieved
future: <Task finished coro=<SwitchController._initialize_switches() done, defined at c:\users\noah\mpfenv\lib\site-packages\mpf\core\switch_controller.py:79> exception=AttributeError("'NoneType' object has no attribute 'number'")>
Traceback (most recent call last):
  File "c:\users\noah\mpfenv\lib\site-packages\mpf\core\switch_controller.py", line 81, in _initialize_switches
    await self.update_switches_from_hw()
  File "c:\users\noah\mpfenv\lib\site-packages\mpf\core\switch_controller.py", line 103, in update_switches_from_hw
    switches.add((switch, switch.hw_switch.number))
AttributeError: 'NoneType' object has no attribute 'number'
2021-03-30 18:13:43,199 : ERROR : Machine : Runtime Exception
Traceback (most recent call last):
  File "c:\users\noah\mpfenv\lib\site-packages\mpf\core\machine.py", line 745, in _run_loop
    raise self._exception['exception']
  File "c:\users\noah\mpfenv\lib\site-packages\mpf\core\system_wide_device.py", line 17, in device_added_system_wide
    await self._initialize()
  File "c:\users\noah\mpfenv\lib\site-packages\mpf\devices\switch.py", line 148, in _initialize
    self.config['number'], config, self.config['platform_settings'])
  File "c:\users\noah\mpfenv\lib\site-packages\mpf\platforms\p3_roc.py", line 371, in configure_switch
    proc_num = self.pdbconfig.get_proc_switch_number(str(number))
  File "c:\users\noah\mpfenv\lib\site-packages\mpf\platforms\p_roc_common.py", line 1193, in get_proc_switch_number
    switch = PDBSwitch(self, number_str)
  File "c:\users\noah\mpfenv\lib\site-packages\mpf\platforms\p_roc_devices.py", line 226, in __init__
    print( self.machine_type );
AttributeError: 'PDBSwitch' object has no attribute 'machine_type'
2021-03-30 18:13:43,201 : INFO : root : MPF run loop ended.
